### ISSUE TITLE
Review-SRS-Team26

### ISSUE THREAD

**Issue by abrahamtaha1** [edwin-do/capstoneTeam30#14]
1. GUI is mentioned numerous times throughout the document however, the acronym is not mentioned in the naming conventions and terminology. 

2. Under the scope of the work section it is mentioned that the sample rate can be set by the user but a maximum number of samples is not clearly mentioned.

3. NFR-U2 the fit criterion for this requirement states that the time to change a parameter in the interface should take no longer than 5 seconds from when the user starts thinking about it. However this is not quantifiable since you can not accurately measure when a user thinks about something. Rather something such as the task should take 5 seconds from when the user touches the mouse would be more realistic.

4. NFR-M2 states that the product will be supported on both windows 7 and windows 10 however under section 4.4-Tasks it only includes a task of compatibility for windows 7.

5. 2.1.1 context diagram can be expanded to include the event path of a user accessing the program remotely since the scope of the work mentions having remote accessibility as a goal of the project

6. Section 4.6-Risks mentions that the computers in the lab don’t require a network connection. Has the group thought about how to incorporate a remote access functionality to the program when a network connection is not available? Furthermore, if the network connection is actually available but just unused, will setting up that connection create supportability issues with the operating systems of the lab computers?

7. NFR-P4 - Given the measurements are read accurately to 3 decimal places (according to NFR-P3), if there are complex calculations regarding these measurements you might lose more than 1 digit of accuracy. Might not be able to logically prove the accuracy of final results if the display is only accurate to 2 decimal places.

**Comment by SirWolffe** [comment]
All points have been addressed.

**Comment by edwin-do** [comment]
Merged
