### ISSUE TITLE
Team 30 Review - Abstracting rationale from requirements 

### ISSUE THREAD

**Issue by muhanadsada** [edwin-do/capstoneTeam30#29]
Try to separate the rationale from the requirements for example, in SFR1, you can have the requirement as 'Graphics shall avoid changing brightness at a rapid rate' and the rationale would be 'To avoid increasing the risk of seizures'

**Comment by tmag15** [comment]
Added in Final Revision - Awaiting merge before closing issue

**Comment by edwin-do** [comment]
Merged
