### ISSUE TITLE
Review-HAZ-Team[30]

### ISSUE THREAD

**Issue by stoh1729** [edwin-do/capstoneTeam30#30]
The reviewer's capstone group TA is @tomashetMcMaster.
In the FMEA table, component "Serial Connection", the effects of failure for this component can be clearer why this effect is considered a failure to the user.

I think that "Data cannot be communicated to App" only describes a failure in the systems functionality. I think you could consider saying something along the lines of "User will miss changes in the sample during a test" as an example of highlighting how the user would experiences serial communication failure.

**Comment by seddikia0** [comment]
Done (replaced with "User will miss changes in the sample during a test")

**Comment by edwin-do** [comment]
Merged
