### ISSUE TITLE
Review-HAZ-Team[30]

### ISSUE THREAD

**Issue by stoh1729** [edwin-do/capstoneTeam30#31]
The reviewer's capstone group TA is @tomashetMcMaster.
In the FMEA table, components such as Current Source, Nanovoltmeter, Temperature Sensor as examples, have the vague recommended action bullet point "Troubleshoot current source setup".

I think that "Troubleshoot current source setup" seems vague because the user does not necessarily know how to act on the failure after reading the recommended action. A possible consideration for hardware related troubleshooting that has a more specific action item could be "User verifies the current hardware connections between devices matches schematic".

**Comment by seddikia0** [comment]
Added instructions to check the manuals

**Comment by edwin-do** [comment]
Merged
