### ISSUE TITLE
Review-HAZ-Team[30]

### ISSUE THREAD

**Issue by TioluwaB** [edwin-do/capstoneTeam30#33]
The reviewer's capstone group TA is @tomashetMcMaster.
Your critical assumptions are clear but do not really have that much information regarding them, I would try add a little more detail or even explain why these assumptions are being made. Even possibly give examples of failures that these critical assumptions help avoid.

**Comment by edwin-do** [comment]
Added in Final Revision - Awaiting merge before closing issue

**Comment by edwin-do** [comment]
Merged
