### ISSUE TITLE
Research lab equipment - Safety

### ISSUE THREAD

**Issue by edwin-do** [edwin-do/capstoneTeam30#7]
Look into what safety precautions we need to have so that we can inform Dr.Zurob before using the equipment

**Comment by seddikia0** [comment]
I've used this document (https://www.osha.gov/sites/default/files/2019-04/Basic_Electricity_Materials.pdf) to write a few precaution points.

[Electricity Precautions.pdf](https://github.com/edwin-do/capstoneTeam30/files/9702023/Electricity.Precautions.pdf)
