### ISSUE TITLE
Team 23 Design Doc Review #1

### ISSUE THREAD

**Issue by Womfidence** [edwin-do/capstoneTeam30#77]
Software Architecture: MG
You showcase a traceability matrix to highlight which requirements are fulfilled by which modules, but it is unclear to a first-time reader what those requirements are. Consider adding a hyperlink/reference to your SRS when these requirements are referenced.

**Comment by seddikia0** [comment]
Added hyperlink to SRS doc within the word "requirements"

**Comment by edwin-do** [comment]
Merged
