### ISSUE TITLE
Team 23 Design Doc Review #2

### ISSUE THREAD

**Issue by LemonU-mcmaster** [edwin-do/capstoneTeam30#78]
Section 1 of reflection in the System Design document does not seem to answer the question.

The question asks for the limitation in the __solution__, whereas the team's response seems to describe the limitation in the __given hardware__ that the solution have to cope with, but __not about the solution itself__.

**Comment by tmag15** [comment]
Added in final - awaiting merge

**Comment by edwin-do** [comment]
Merged
