### ISSUE TITLE
Team 23 Design Doc Review #3

### ISSUE THREAD

**Issue by Womfidence** [edwin-do/capstoneTeam30#79]
Software Architecture: MG
The structure of some of your modules is unclear; you reference a Hardware-Hiding module in Section 5 Module Decomposition, but you do not relate it to any of your requirements in Section 8 or showcase its Use Hierarchy in Section 9. If the module isn't necessary/unique to your system, consider leaving the Hardware Hiding section of the module decomposition blank/state how it doesn't relate to your final product

**Comment by edwin-do** [comment]
Implemented internally - awaiting merge

**Comment by edwin-do** [comment]
Merged
