### ISSUE TITLE
Team 23 Design Doc Review #4

### ISSUE THREAD

**Issue by LemonU-mcmaster** [edwin-do/capstoneTeam30#80]
There should be an additional exported access routine in the Remote Access module that provides the transmission of data/execution directives to the remote system.

Currently, the module only provides `connect()` and `disconnect()`, which are reasonable as to establish/terminate the connection to the remote system. But once the connection to the remote system is up, there should be data transmission to/from the remote system or otherwise there's no point for setting up the remote connection. Thus, there should be an addtional method (maybe named `transmit(data: bytes[]): bytes[]`?) for doing such transmission.

**Comment by edwin-do** [comment]
Revised Remote Access module internally - awaiting merge

**Comment by edwin-do** [comment]
Merged
